on:
  create:
jobs:
  github-example-tags:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=${ GITHUB_REF_NAME#v }
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      # Use version in other step
      - name: Read version
        run: |
          echo Version now: ${VERSION}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Release v${{ env.VERSION }}"
          files: |
            test
            *.txt
